In [1]:
import numpy as np

In [2]:
class Neural_Network(object):
    def __init__(self):
        # Define HyperParameters         
        self.inputLayerSize = 2
        self.outputLayerSize = 1
        self.hiddenLayerSize = 3
        # Weight Parameters         
        self.W1 = np.random.randn(self.inputLayerSize, self.hiddenLayerSize)
        self.W2 = np.random.randn(self.hiddenLayerSize, self.outputLayerSize)
    
    def forward(self, X):
        self.z2 = np.dot(X, self.W1)
        self.a2 = self.sigmoid(self.z2)
        self.z3 = np.dot(self.a2, self.W2)
        yHat = self.sigmoid(self.z3)
        return yHat
        
    def sigmoid(self, z):
        # Sigmoid Function
        return 1/(1+np.exp(-z))
    
    def sigmoidPrime(self, z):
        # Derivative of Sigmoid Function
        return np.exp(-z)/((1+np.exp(-z))**2)
    
    def costFunction(self, X, y):
        print(self.W1, self.W2)
        self.yHat = self.forward(X)
        return 0.5*sum((y-self.yHat) ** 2.)
    
    def costFunctionPrime(self, X, y):
        # Compute Dervivative with respect to W1 and W1
        self.yHat = self.forward(X)

        delta3 = np.multiply(-(y-self.yHat), self.sigmoidPrime(self.z3))
        dJdW2 = np.dot(self.a2.T, delta3)

        delta2 = np.dot(delta3, self.W2.T) * self.sigmoidPrime(self.z2)
        dJdW1 = np.dot(X.T, delta2)

        return dJdW1, dJdW2
    

In [3]:
X = np.array([[3, 5],
              [5, 1],
              [10, 2]], dtype=float)
y = np.array([[75], [82], [93]], dtype=float)

X = X / np.amax(X, axis=0)
y = y / np.amax(y)

NN = Neural_Network()
yHat = NN.forward(X)
print(yHat)

[[ 0.54941723]
 [ 0.58130387]
 [ 0.52699592]]


## Compute the minimal cost for one weight

In [4]:
# import matplotlib.pyplot as plt
# plt.plot(weightsToTry, costs)
# plt.ylabel('Cost')
# plt.xlabel('Weight')
# plt.grid(1)
# plt.show()

In [5]:
NN = Neural_Network()

In [6]:
cost1 = NN.costFunction(X, y)
cost1

[[-0.42306143  0.84865804 -0.93770322]
 [-0.57998232 -0.04542993 -0.24355367]] [[-0.05224446]
 [ 2.78420802]
 [-0.0326683 ]]


array([ 0.00931335])

In [7]:
dJdW1, dJdW2 = NN.costFunctionPrime(X, y)

In [8]:
dJdW1, dJdW2

(array([[  2.01082172e-04,  -1.00984574e-02,   1.09709742e-04],
        [  6.19011340e-05,  -2.93531004e-03,   3.16492589e-05]]),
 array([[-0.00682065],
        [-0.01262378],
        [-0.00532431]]))

In [9]:
# print(NN.W1, NN.W2)
scalar = 3
NN.W1 = NN.W1 + scalar*dJdW1
NN.W2 = NN.W2 + scalar*dJdW2
print(NN.W1, NN.W2)
cost2 = NN.costFunction(X, y)
cost2

[[-0.42245818  0.81836267 -0.93737409]
 [-0.57979662 -0.05423586 -0.24345872]] [[-0.07270639]
 [ 2.74633669]
 [-0.04864124]]
[[-0.42245818  0.81836267 -0.93737409]
 [-0.57979662 -0.05423586 -0.24345872]] [[-0.07270639]
 [ 2.74633669]
 [-0.04864124]]


array([ 0.01043452])

In [10]:
print(cost1, cost2)

[ 0.00931335] [ 0.01043452]
